#ifndef PROXPL_VERSION_H
#define PROXPL_VERSION_H

#define PROXPL_VERSION_MAJOR 1
#define PROXPL_VERSION_MINOR 6
#define PROXPL_VERSION_PATCH 3
#define PROXPL_VERSION_STRING "1.6.3"
#define PROXPL_VERSION_PRERELEASE ""

#endif // PROXPL_VERSION_H
