
def register(vm):
    vm.define_native("len", lambda args: len(args[0]))
    vm.define_native("upper", lambda args: str(args[0]).upper())
    vm.define_native("lower", lambda args: str(args[0]).lower())
    vm.define_native("split", lambda args: str(args[0]).split(args[1] if len(args) > 1 else " "))
    vm.define_native("join", lambda args: str(args[0]).join([str(x) for x in args[1]]))
    vm.define_native("replace", lambda args: str(args[0]).replace(str(args[1]), str(args[2])))
    vm.define_native("trim", lambda args: str(args[0]).strip())
    vm.define_native("startswith", lambda args: str(args[0]).startswith(str(args[1])))
    vm.define_native("endswith", lambda args: str(args[0]).endswith(str(args[1])))
    vm.define_native("contains", lambda args: str(args[1]) in str(args[0]))
    vm.define_native("index_of", lambda args: str(args[0]).find(str(args[1])))
    vm.define_native("substring", lambda args: str(args[0])[int(args[1]):int(args[2]) if len(args) > 2 else None])
    vm.define_native("format", lambda args: str(args[0]).format(*args[1:]))
    vm.define_native("char_at", lambda args: str(args[0])[int(args[1])])
    vm.define_native("to_bytes", lambda args: bytes(str(args[0]), 'utf-8'))
