#ifndef PROX_SCANNER_H
#define PROX_SCANNER_H

typedef enum {
  // Single-character tokens
  TOKEN_LEFT_PAREN,
  TOKEN_RIGHT_PAREN,
  TOKEN_LEFT_BRACE,
  TOKEN_RIGHT_BRACE,
  TOKEN_LEFT_BRACKET,
  TOKEN_RIGHT_BRACKET,
  TOKEN_COMMA,
  TOKEN_DOT,
  TOKEN_MINUS,
  TOKEN_PLUS,
  TOKEN_SEMICOLON,
  TOKEN_SLASH,
  TOKEN_STAR,
  TOKEN_PERCENT,
  TOKEN_QUESTION,
  TOKEN_COLON,
  TOKEN_BANG,
  TOKEN_TILDE,
  TOKEN_AMPERSAND,
  TOKEN_PIPE,
  TOKEN_CARET,

  // One or two character tokens
  TOKEN_BANG_EQUAL,
  TOKEN_EQUAL,
  TOKEN_EQUAL_EQUAL,
  TOKEN_GREATER,
  TOKEN_GREATER_EQUAL,
  TOKEN_GREATER_GREATER,
  TOKEN_LESS,
  TOKEN_LESS_EQUAL,
  TOKEN_LESS_LESS,
  TOKEN_PLUS_PLUS,
  TOKEN_MINUS_MINUS,
  TOKEN_PLUS_EQUAL,
  TOKEN_MINUS_EQUAL,
  TOKEN_STAR_EQUAL,
  TOKEN_SLASH_EQUAL,
  TOKEN_PERCENT_EQUAL,
  TOKEN_AMPERSAND_EQUAL,
  TOKEN_PIPE_EQUAL,
  TOKEN_CARET_EQUAL,
  TOKEN_AMPERSAND_AMPERSAND,
  TOKEN_PIPE_PIPE,
  TOKEN_DOT_DOT,
  TOKEN_QUESTION_DOT,
  TOKEN_QUESTION_QUESTION,
  TOKEN_ARROW,
  TOKEN_STAR_STAR,

  // Three character tokens
  TOKEN_STAR_STAR_EQUAL,
  TOKEN_LESS_LESS_EQUAL,
  TOKEN_GREATER_GREATER_EQUAL,

  // Literals
  TOKEN_IDENTIFIER,
  TOKEN_STRING,
  TOKEN_NUMBER,

  // Keywords
  TOKEN_AND,
  TOKEN_CLASS,
  TOKEN_ELSE,
  TOKEN_FALSE,
  TOKEN_FOR,
  TOKEN_FUNC,
  TOKEN_IF,
  TOKEN_NULL,
  TOKEN_OR,
  TOKEN_PRINT,
  TOKEN_RETURN,
  TOKEN_SUPER,
  TOKEN_THIS,
  TOKEN_TRUE,
  TOKEN_LET,
  TOKEN_CONST,
  TOKEN_WHILE,
  TOKEN_BREAK,
  TOKEN_CONTINUE,
  TOKEN_SWITCH,
  TOKEN_CASE,
  TOKEN_DEFAULT,
  TOKEN_TRY,
  TOKEN_CATCH,
  TOKEN_FINALLY,
  TOKEN_THROW,
  TOKEN_ASYNC,
  TOKEN_AWAIT,
  TOKEN_USE,
  TOKEN_IMPORT,
  TOKEN_EXPORT,
  TOKEN_FROM,
  TOKEN_AS,
  TOKEN_IN,
  TOKEN_IS,
  TOKEN_TYPEOF,
  TOKEN_EXTENDS,
  TOKEN_IMPLEMENTS,
  TOKEN_INTERFACE,
  TOKEN_ENUM,
  TOKEN_STRUCT,
  TOKEN_STATIC,
  TOKEN_PUBLIC,
  TOKEN_PRIVATE,
  TOKEN_PROTECTED,
  TOKEN_ABSTRACT,
  TOKEN_NATIVE,
  TOKEN_VOID,
  TOKEN_DEFER,

  TOKEN_ERROR,
  TOKEN_EOF
} TokenType;

typedef struct {
  TokenType type;
  const char *start;
  int length;
  int line;
} Token;

typedef struct {
  const char *start;
  const char *current;
  int line;
} Scanner;

void initScanner(Scanner *scanner, const char *source);
Token scanToken(Scanner *scanner);

#endif
